function handler(m) {
  this.reply(m.chat, '🔰 ADVANCED WEB HACKING TOOLS🔰\n●Havij\n●NetDatabaseScanner\n●Open Web Spider\n●Quick Web\n●Site Hog\n●Snippets Manager\n●Spider Mail\n●SQL Injection\n●SQL Map Project\n●The Mole ZeroTeam™ MD5 Password Encryptor\n●Acunetix Web Vulnerability Scanner\n●Advanced Deface Creator 1.3\n●Anonymous DNS Extractor-2013\n●Anonymous FTP Stealer\n●Anonymous Text Encrypter\n●Anonymous Tinypaste Uploader\n●Ashiyane SQL Scanner\n●Base64 Image Encoder-Decoder\n●BTI Admin Page Finder v2\n●BTI HTML Encoder-Decoder\n●BTI Multi Site Checker\n●BTI Reverse IP Domain Check v2\n●ChromePasswordDecryptor\n●CSS Minifier v2\n●Deface Page Created\n●Dork Searcher Setup v1091\n●dorkinj\n●DorkTools\n●Eternals WebBrowser\n●Explode Web Scanner\n●ezDataBase_Defacer\n●Fiddler Web Debugger Setup\n●Gklspy\n●Google URL Extractor\n●Gr3eNoX LFi Exploiter\n●Hacker’s Browser v2.0\n●Injection Framework – Automatized Sql\n●Injection Tool\n●Iron Web application Advanced Security\n●testing Platform\n●Joomla Security Scanner\n●JSQL-Injection\n●Mass Dork Scanner v1.0.0.1\n●Multi Vuln Checker\n●nmap\n●Spider Mail\n●SQL Exploiter Pro v2.10\n●SQL Helper\n●SQLI-Hunter_v1.1\n●SQLI-Hunter_v1.2\n●SQL-Inject-Me-master\n●sqlmap_win_v01●sqlmap-0.9\n●sqlninja-0.2.6-r1\n●SQLSentinel_v_0.3\n●Surf Excuse\n●Survey Bypasser\n●Tiny URL Shortener\n●Vulcan Cleaner\n●Vuln Hunter\n●vulnerability master\n●wapiti-2.3.0-win32-standalone\n●Warbot VersaoSQL Tool v1.0 Alpha Build 6\n●Web Source Tools\n●WebCruiser\n●WebCruiserPro\n●Websecurity Scanner 0.9\n●Website Blocker v2\n●WebSurgery-Setup-1.1.1\n●XCodeExploitScannerSept\n●xSQL SCanner\nhttps://www.mediafire.com/file/r3k2vhkv2ihczwz/Advance_Web_hacking_tools.rar/file\nEnjoy and Thank me later ❤️', m)
}
handler.help = ['AdvanceWebsiteHackingTools']
handler.tags = ['info']

handler.command = /^(AdvanceWebsiteHackingTools|advancewebsitehackingtools)$/i

module.exports = handler
