function handler(m) {
  this.reply(m.chat, 'Biggest Collection Ever !!!\n▪️CARDING COURSE\nDownload by\nhttps://mega.nz/file/QDRkhYQb#bEq1NEH274Xxf5u_S2tuIxvO9YUWSJjsm6HVmbL0Yss\n▪️ETHICAL HACKING COMPLETE BOOKS  (2.32 GB OF PDF & EBOOKS)\nDownload by\nhttps://mega.nz/folder/l9MXSYoI#zXBSvykjca7FkCYH6Flcow\n▪️ MASTERS IN ETHICAL HACKING COURSE\nDownload by\nhttps://www.mediafire.com/file/6s6l144339ja2yl/Masters-In-Ethical-Hacking-Course-2-Gib-.7z/file\n▪ BLACK HAT CRACKING COURSE (NETFLIX, AMAZON PRIMZE, HOTSTAR CRACKING)\nDownload by\nhttps://drive.google.com/drive/folders/17KyX_80h0yBUrc3X-PMa3EnXoE0kFmJJ?sort=13&direction=a\n▪️ DEDSEC COURSES (WIFI HACKING, ANDROID HACKING, BLACKHAT HACKING, HACKING REVERSE ENGINEERING, CRACKING, KALI LINUX)\nDownload by\nhttps://drive.google.com/open?id=1k_GdJtXMC-xyG-Rk-H0qEnqxZwX1R1p3\n▪ LEARN WEBSITE HACKING\nDownload by\nhttps://mega.nz/folder/3ipEGIzZ#VAvV7N8XZHD-sZ3RULvI9g\n▪️ COMPLETE HACKING WITH TERMUX COURSE\nDownload by\nhttps://drive.google.com/file/d/148LXyQr03aSGibq8-Juo_IqYm-DjsgOL/view\n▪️ BUG BOUNTY ANDROID Hacking\nDownload by\nhttps://mega.nz/#F!h4hHGIYa!2ta4n94iQNnVzpJToVPLVw\n▪️ UDEMY BURP SUITE BUG BOUNTY WEB HACKING FROM SCRATCH\nDownload by\nhttps://drive.google.com/file/d/1eWy5HVLw3tvw4lfsT7kYb5dnD1l0RsoW/view\n▪️ UDEMY BUG BOUNGY HUNTING GUIDE TO ADVANCED EARNING METHOD\nDownload by\nhttps://drive.google.com/drive/folders/1t-hTqg0-02t0cnc5SypHnb8t3CfE3bXU\n▪️ ULTIMATE CYBER SECURITY COURSE (10GB PACKAGE)\nDownload by\nhttps://drive.google.com/drive/folders/0ByzazsLLzvFwLVNfSW5BeS0yLTg\n▪️ BLACK RADIATORS COMPLETE ETHICAL HACKING COURSE BEGINNER TO ADVANCED\nDownload by\nhttps://mega.nz/#F!W4B22QwL!ASup26IJ_Cls6JD2_wfRpg\n▪️ BLACK HAT HACKING TOOLS (COLLECTION OF 5GB)\nDownload by\nhttps://mega.nz/file/IchVABiT#3XiWE_C2X2fd8wR1MyQ1LPC3FU-DQVP9a6uuzO37ztU\n▪️ GREY HAT HACKING BOOK:\nDownload by\nhttps://drive.google.com/file/d/0Bw1xURlCeiXiQXphUzlLTV8xWmM/view\n▪️ DUTCHMAN COURSE\nDownload by\nhttp://www.mediafire.com/file/6yhalmkfdbs9njs/DUTCHMAN_FULL_COURSE_PACK_&_DELETED_VIDEOS.rar/file\n▪️ CARDING PACK FOR FREE 2018\nDownload by\nhttps://drive.google.com/file/d/1qfvgk7C3sP3KWoH-iHGG2EHNoCaWisIg/view?usp=drivesdk\nPass: abcd\n▪️ DEDSEC SPAMMING COURSE\nDownload by\nhttps://mega.nz/folder/AJFyXAAR#8vREaia6WbnR3xyp9XfsVQ\n◾ TECH MASTEer\nDownload by\bhttps://www.mediafire.com/file/umk316gpoy3tlbg/Tech_Master.zip/file\n◾ QUICK HACK COURSE\nDownload by\nhttps://www.mediafire.com/file/mrcz8aa7ji05a2m/Quick_Hack_-_Beginners_Ethical_Hacking_Course_%28White_Hat%29.zip/file\n◾ MONEY MAKING COURSE\nDownload by\nhttp://www.mediafire.com/file/9scal11vbu97tyo/Money_Making.zip/file\n◾ DELETED VIDEO COURSE\nDownload by\nhttps://www.mediafire.com/file/3gn3h848vpfqflz/Deleted_Videos.zip/file', m)
}
handler.help = ['MegaCourses2']
handler.tags = ['info']

handler.command = /^(MegaCourses2|megacourses2)$/i

module.exports = handler
